const keyboardLayouts = {
	en: [
		[
			{ code: 'Backquote', key: '§', shiftKey: '±' },
			{ code: 'Digit1', key: '1', shiftKey: '!' },
			{ code: 'Digit2', key: '2', shiftKey: '@' },
			{ code: 'Digit3', key: '3', shiftKey: '#' },
			{ code: 'Digit4', key: '4', shiftKey: '$' },
			{ code: 'Digit5', key: '5', shiftKey: '%' },
			{ code: 'Digit6', key: '6', shiftKey: '^' },
			{ code: 'Digit7', key: '7', shiftKey: '&' },
			{ code: 'Digit8', key: '8', shiftKey: '*' },
			{ code: 'Digit9', key: '9', shiftKey: '(' },
			{ code: 'Digit0', key: '0', shiftKey: ')' },
			{ code: 'Minus', key: '-', shiftKey: '_' },
			{ code: 'Equal', key: '=', shiftKey: '+' },
			{ code: 'Backspace', key: '⌫', action: 'Backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'Tab' },
			{ code: 'KeyQ', key: 'q', shiftKey: 'Q' },
			{ code: 'KeyW', key: 'w', shiftKey: 'W' },
			{ code: 'KeyE', key: 'e', shiftKey: 'E' },
			{ code: 'KeyR', key: 'r', shiftKey: 'R' },
			{ code: 'KeyT', key: 't', shiftKey: 'T' },
			{ code: 'KeyY', key: 'y', shiftKey: 'Y' },
			{ code: 'KeyU', key: 'u', shiftKey: 'U' },
			{ code: 'KeyI', key: 'i', shiftKey: 'I' },
			{ code: 'KeyO', key: 'o', shiftKey: 'O' },
			{ code: 'KeyP', key: 'p', shiftKey: 'P' },
			{ code: 'BracketLeft', key: '[', shiftKey: '{' },
			{ code: 'BracketRight', key: ']', shiftKey: '}' },
			{ code: 'Enter', key: '↵', action: 'Enter' },
		],
		[
			{ code: 'CapsLock', key: '⇪', action: 'CapsLock' },
			{ code: 'KeyA', key: 'a', shiftKey: 'A' },
			{ code: 'KeyS', key: 's', shiftKey: 'S' },
			{ code: 'KeyD', key: 'd', shiftKey: 'D' },
			{ code: 'KeyF', key: 'f', shiftKey: 'F' },
			{ code: 'KeyG', key: 'g', shiftKey: 'G' },
			{ code: 'KeyH', key: 'h', shiftKey: 'H' },
			{ code: 'KeyJ', key: 'j', shiftKey: 'J' },
			{ code: 'KeyK', key: 'k', shiftKey: 'K' },
			{ code: 'KeyL', key: 'l', shiftKey: 'L' },
			{ code: 'Semicolon', key: ';', shiftKey: ':' },
			{ code: 'Quote', key: "'", shiftKey: '"' },
			{ code: 'Backslash', key: '\\', shiftKey: '|' },
		],
		[
			{ code: 'ShiftLeft', key: '⇧', action: 'Shift' },
			{ code: 'IntlBackslash', key: '`', shiftKey: '~' },
			{ code: 'KeyZ', key: 'z', shiftKey: 'Z' },
			{ code: 'KeyX', key: 'x', shiftKey: 'X' },
			{ code: 'KeyC', key: 'c', shiftKey: 'C' },
			{ code: 'KeyV', key: 'v', shiftKey: 'V' },
			{ code: 'KeyB', key: 'b', shiftKey: 'B' },
			{ code: 'KeyN', key: 'n', shiftKey: 'N' },
			{ code: 'KeyM', key: 'm', shiftKey: 'M' },
			{ code: 'Comma', key: ',', shiftKey: '<' },
			{ code: 'Period', key: '.', shiftKey: '>' },
			{ code: 'Slash', key: '/', shiftKey: '?' },
			{ code: 'ShiftRight', key: '⇧', action: 'Shift' },
		],
		[
			{ code: 'ControlLeft', key: '⌃', action: 'Ctrl' },
			{ code: 'AltLeft', key: '⌥', action: 'Alt' },
			{ code: 'MetaLeft', key: '⌘', action: 'Meta' },
			{ code: 'Space', key: ' ', shiftKey: ' ' },
			{ code: 'MetaRight', key: '⌘', action: 'Meta' },
			{ code: 'AltRight', key: '⌥', action: 'Alt' },
			{ code: 'ArrowLeft', key: '←', action: 'ArrowLeft' },
			{ code: 'ArrowUp', key: '↑', action: 'ArrowUp' },
			{ code: 'ArrowDown', key: '↓', action: 'ArrowDown' },
			{ code: 'ArrowRight', key: '→', action: 'ArrowRight' },
		],
	],
	ru: [
		[
			{ code: 'Backquote', key: '>', shiftKey: '<' },
			{ code: 'Digit1', key: '1', shiftKey: '!' },
			{ code: 'Digit2', key: '2', shiftKey: '"' },
			{ code: 'Digit3', key: '3', shiftKey: '№' },
			{ code: 'Digit4', key: '4', shiftKey: '%' },
			{ code: 'Digit5', key: '5', shiftKey: ':' },
			{ code: 'Digit6', key: '6', shiftKey: ',' },
			{ code: 'Digit7', key: '7', shiftKey: '.' },
			{ code: 'Digit8', key: '8', shiftKey: ';' },
			{ code: 'Digit9', key: '9', shiftKey: '(' },
			{ code: 'Digit0', key: '0', shiftKey: ')' },
			{ code: 'Minus', key: '-', shiftKey: '_' },
			{ code: 'Equal', key: '=', shiftKey: '+' },
			{ code: 'Backspace', key: '⌫', action: 'Backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'Tab' },
			{ code: 'KeyQ', key: 'й', shiftKey: 'Й' },
			{ code: 'KeyW', key: 'ц', shiftKey: 'Ц' },
			{ code: 'KeyE', key: 'у', shiftKey: 'У' },
			{ code: 'KeyR', key: 'к', shiftKey: 'К' },
			{ code: 'KeyT', key: 'е', shiftKey: 'Е' },
			{ code: 'KeyY', key: 'н', shiftKey: 'Н' },
			{ code: 'KeyU', key: 'г', shiftKey: 'Г' },
			{ code: 'KeyI', key: 'ш', shiftKey: 'Ш' },
			{ code: 'KeyO', key: 'щ', shiftKey: 'Щ' },
			{ code: 'KeyP', key: 'з', shiftKey: 'З' },
			{ code: 'BracketLeft', key: 'х', shiftKey: 'Х' },
			{ code: 'BracketRight', key: 'ъ', shiftKey: 'Ъ' },
			{ code: 'Enter', key: '↵', action: 'Enter' },
		],
		[
			{ code: 'CapsLock', key: '⇪', action: 'CapsLock' },
			{ code: 'KeyA', key: 'ф', shiftKey: 'Ф' },
			{ code: 'KeyS', key: 'ы', shiftKey: 'Ы' },
			{ code: 'KeyD', key: 'в', shiftKey: 'В' },
			{ code: 'KeyF', key: 'а', shiftKey: 'А' },
			{ code: 'KeyG', key: 'п', shiftKey: 'П' },
			{ code: 'KeyH', key: 'р', shiftKey: 'Р' },
			{ code: 'KeyJ', key: 'о', shiftKey: 'О' },
			{ code: 'KeyK', key: 'л', shiftKey: 'Л' },
			{ code: 'KeyL', key: 'д', shiftKey: 'Д' },
			{ code: 'Semicolon', key: 'ж', shiftKey: 'Ж' },
			{ code: 'Quote', key: 'э', shiftKey: 'Э' },
			{ code: 'Backslash', key: 'ё', shiftKey: 'Ё' },
		],
		[
			{ code: 'ShiftLeft', key: '⇧', action: 'Shift' },
			{ code: 'IntlBackslash', key: ']', shiftKey: '[' },
			{ code: 'KeyZ', key: 'я', shiftKey: 'Я' },
			{ code: 'KeyX', key: 'ч', shiftKey: 'Ч' },
			{ code: 'KeyC', key: 'с', shiftKey: 'С' },
			{ code: 'KeyV', key: 'м', shiftKey: 'М' },
			{ code: 'KeyB', key: 'и', shiftKey: 'И' },
			{ code: 'KeyN', key: 'т', shiftKey: 'Т' },
			{ code: 'KeyM', key: 'ь', shiftKey: 'Ь' },
			{ code: 'Comma', key: 'б', shiftKey: 'Б' },
			{ code: 'Period', key: 'ю', shiftKey: 'Ю' },
			{ code: 'Slash', key: '/', shiftKey: '?' },
			{ code: 'ShiftRight', key: '⇧', action: 'Shift' },
		],
		[
			{ code: 'ControlLeft', key: '⌃', action: 'Ctrl' },
			{ code: 'AltLeft', key: '⌥', action: 'Alt' },
			{ code: 'MetaLeft', key: '⌘', action: 'Meta' },
			{ code: 'Space', key: ' ', shiftKey: ' ' },
			{ code: 'MetaRight', key: '⌘', action: 'Meta' },
			{ code: 'AltRight', key: '⌥', action: 'Alt' },
			{ code: 'ArrowLeft', key: '←', action: 'ArrowLeft' },
			{ code: 'ArrowUp', key: '↑', action: 'ArrowUp' },
			{ code: 'ArrowDown', key: '↓', action: 'ArrowDown' },
			{ code: 'ArrowRight', key: '→', action: 'ArrowRight' },
		],
	],
}

export default keyboardLayouts
