const keyboardLayouts = {
	en: [
		[
			{ code: 'IntlBackslash', key: '§' },
			{ code: 'Digit1', key: '1'},
			{ code: 'Digit2', key: '2' },
			{ code: 'Digit3', key: '3' },
			{ code: 'Digit4', key: '4' },
			{ code: 'Digit5', key: '5' },
			{ code: 'Digit6', key: '6' },
			{ code: 'Digit7', key: '7' },
			{ code: 'Digit8', key: '8' },
			{ code: 'Digit9', key: '9' },
			{ code: 'Digit0', key: '0' },
			{ code: 'Minus', key: '-' },
			{ code: 'Equal', key: '=' },
			{ code: 'Backspace', key: '⌫', action: 'backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'tab' },
			{ code: 'KeyQ', key: 'q' },
			{ code: 'KeyW', key: 'w' },
			{ code: 'KeyE', key: 'e' },
			{ code: 'KeyR', key: 'r' },
			{ code: 'KeyT', key: 't' },
			{ code: 'KeyY', key: 'y' },
			{ code: 'KeyU', key: 'u' },
			{ code: 'KeyI', key: 'i' },
			{ code: 'KeyO', key: 'o' },
			{ code: 'KeyP', key: 'p' },
			{ code: 'BracketLeft', key: '[' },
			{ code: 'BracketRight', key: ']' },
			{ code: 'Enter', key: '↵', action: 'enter' },
		],
		[
			{ code: 'CapsLock', key: '⇪', action: 'capslock' },
			{ code: 'KeyA', key: 'a' },
			{ code: 'KeyS', key: 's' },
			{ code: 'KeyD', key: 'd' },
			{ code: 'KeyF', key: 'f' },
			{ code: 'KeyG', key: 'g' },
			{ code: 'KeyH', key: 'h' },
			{ code: 'KeyJ', key: 'j' },
			{ code: 'KeyK', key: 'k' },
			{ code: 'KeyL', key: 'l' },
			{ code: 'Semicolon', key: ';' },
			{ code: 'Quote', key: "'" },
			{ code: 'Backslash', key: '\\' },
		],
		[
			{ code: 'ShiftLeft', key: '⇧', action: 'shift' },
			{ code: 'Backquote', key: '`' },
			{ code: 'KeyZ', key: 'z' },
			{ code: 'KeyX', key: 'x' },
			{ code: 'KeyC', key: 'c' },
			{ code: 'KeyV', key: 'v' },
			{ code: 'KeyB', key: 'b' },
			{ code: 'KeyN', key: 'n' },
			{ code: 'KeyM', key: 'm' },
			{ code: 'Comma', key: ',' },
			{ code: 'Period', key: '.' },
			{ code: 'Slash', key: '/' },
			{ code: 'ShiftRight', key: '⇧', action: 'shift' },
		],
		[
			{ code: 'ControlLeft', key: '⌃', action: 'ctrl' },
			{ code: 'AltLeft', key: '⌥', action: 'alt' },
			{ code: 'MetaLeft', key: '⌘', action: 'meta' },
			{ code: 'Space', key: '␣', action: 'space' },
			{ code: 'MetaRight', key: '⌘', action: 'meta' },
			{ code: 'AltRight', key: '⌥', action: 'alt' },
			{ code: 'ArrowLeft', key: '←', action: 'left' },
			{ code: 'ArrowUp', key: '↑', action: 'up' },
			{ code: 'ArrowDown', key: '↓', action: 'down' },
			{ code: 'ArrowRight', key: '→', action: 'right' },
		],
	],

	ru: [
		[
			{ code: 'IntlBackslash', key: 'ё' },
			{ code: 'Digit1', key: '1' },
			{ code: 'Digit2', key: '2' },
			{ code: 'Digit3', key: '3' },
			{ code: 'Digit4', key: '4' },
			{ code: 'Digit5', key: '5' },
			{ code: 'Digit6', key: '6' },
			{ code: 'Digit7', key: '7' },
			{ code: 'Digit8', key: '8' },
			{ code: 'Digit9', key: '9' },
			{ code: 'Digit0', key: '0' },
			{ code: 'Minus', key: '-' },
			{ code: 'Equal', key: '=' },
			{ code: 'Backspace', key: '⌫', action: 'backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'tab' },
			{ code: 'KeyQ', key: 'й' },
			{ code: 'KeyW', key: 'ц' },
			{ code: 'KeyE', key: 'у' },
			{ code: 'KeyR', key: 'к' },
			{ code: 'KeyT', key: 'е' },
			{ code: 'KeyY', key: 'н' },
			{ code: 'KeyU', key: 'г' },
			{ code: 'KeyI', key: 'ш' },
			{ code: 'KeyO', key: 'щ' },
			{ code: 'KeyP', key: 'з' },
			{ code: 'BracketLeft', key: 'х' },
			{ code: 'BracketRight', key: 'ъ' },
			{ code: 'Enter', key: '↵', action: 'enter' },
		],
		[
			[
				{ code: 'CapsLock', key: '⇪', action: 'capslock' },
				{ code: 'KeyF', key: 'ф' },
				{ code: 'KeyS', key: 'ы' },
				{ code: 'KeyT', key: 'в' },
				{ code: 'KeyU', key: 'а' },
				{ code: 'KeyH', key: 'п' },
				{ code: 'KeyR', key: 'р' },
				{ code: 'KeyK', key: 'о' },
				{ code: 'KeyL', key: 'л' },
				{ code: 'Semicolon', key: 'д' },
				{ code: 'Quote', key: 'ж' },
				{ code: 'Backslash', key: 'э' },
			],
			[
				{ code: 'ShiftLeft', key: '⇧', action: 'shift' },
				{ code: 'Backquote', key: 'ё' },
				{ code: 'KeyY', key: 'я' },
				{ code: 'KeyC', key: 'с' },
				{ code: 'KeyD', key: 'и' },
				{ code: 'KeyV', key: 'в' },
				{ code: 'KeyJ', key: 'й' },
				{ code: 'KeyG', key: 'г' },
				{ code: 'KeyM', key: 'м' },
				{ code: 'Comma', key: 'ь' },
				{ code: 'Period', key: 'ъ' },
				{ code: 'Slash', key: '.' },
				{ code: 'ShiftRight', key: '⇧', action: 'shift' },
			],
			[
				{ code: 'ControlLeft', key: '⌃', action: 'ctrl' },
				{ code: 'AltLeft', key: '⌥', action: 'alt' },
				{ code: 'MetaLeft', key: '⌘', action: 'meta' },
				{ code: 'Space', key: '␣', action: 'space' },
				{ code: 'MetaRight', key: '⌘', action: 'meta' },
				{ code: 'AltRight', key: '⌥', action: 'alt' },
				{ code: 'ArrowLeft', key: '←', action: 'left' },
				{ code: 'ArrowUp', key: '↑', action: 'up' },
				{ code: 'ArrowDown', key: '↓', action: 'down' },
				{ code: 'ArrowRight', key: '→', action: 'right' },
			],
		],
	],
}

export default keyboardLayouts
