const keyboardLayouts = {
	en: [
		[
			{ code: 'IntlBackslash', key: '§', shiftKey: '±' },
			{ code: 'Digit1', key: '1', shiftKey: '!' },
			{ code: 'Digit2', key: '2', shiftKey: '@' },
			{ code: 'Digit3', key: '3', shiftKey: '#' },
			{ code: 'Digit4', key: '4', shiftKey: '$' },
			{ code: 'Digit5', key: '5', shiftKey: '%' },
			{ code: 'Digit6', key: '6', shiftKey: '^' },
			{ code: 'Digit7', key: '7', shiftKey: '&' },
			{ code: 'Digit8', key: '8', shiftKey: '*' },
			{ code: 'Digit9', key: '9', shiftKey: '(' },
			{ code: 'Digit0', key: '0', shiftKey: ')' },
			{ code: 'Minus', key: '-', shiftKey: '_' },
			{ code: 'Equal', key: '=', shiftKey: '+' },
			{ code: 'Backspace', key: '⌫', action: 'backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'tab' },
			{ code: 'KeyQ', key: 'q' },
			{ code: 'KeyW', key: 'w' },
			{ code: 'KeyE', key: 'e' },
			{ code: 'KeyR', key: 'r' },
			{ code: 'KeyT', key: 't' },
			{ code: 'KeyY', key: 'y' },
			{ code: 'KeyU', key: 'u' },
			{ code: 'KeyI', key: 'i' },
			{ code: 'KeyO', key: 'o' },
			{ code: 'KeyP', key: 'p' },
			{ code: 'BracketLeft', key: '[', shiftKey: '{' },
			{ code: 'BracketRight', key: ']', shiftKey: '}' },
			{ code: 'Enter', key: '↵', action: 'enter' },
		],
		[
			{ code: 'CapsLock', key: '⇪', action: 'capslock' },
			{ code: 'KeyA', key: 'a' },
			{ code: 'KeyS', key: 's' },
			{ code: 'KeyD', key: 'd' },
			{ code: 'KeyF', key: 'f' },
			{ code: 'KeyG', key: 'g' },
			{ code: 'KeyH', key: 'h' },
			{ code: 'KeyJ', key: 'j' },
			{ code: 'KeyK', key: 'k' },
			{ code: 'KeyL', key: 'l' },
			{ code: 'Semicolon', key: ';', shiftKey: ':' },
			{ code: 'Quote', key: "'", shiftKey: '"' },
			{ code: 'Backslash', key: '\\', shiftKey: '|' },
		],
		[
			{ code: 'ShiftLeft', key: '⇧', action: 'shift' },
			{ code: 'Backquote', key: '`', shiftKey: '~' },
			{ code: 'KeyZ', key: 'z' },
			{ code: 'KeyX', key: 'x' },
			{ code: 'KeyC', key: 'c' },
			{ code: 'KeyV', key: 'v' },
			{ code: 'KeyB', key: 'b' },
			{ code: 'KeyN', key: 'n' },
			{ code: 'KeyM', key: 'm' },
			{ code: 'Comma', key: ',', shiftKey: '<' },
			{ code: 'Period', key: '.', shiftKey: '>' },
			{ code: 'Slash', key: '/', shiftKey: '?' },
			{ code: 'ShiftRight', key: '⇧', action: 'shift' },
		],
		[
			{ code: 'ControlLeft', key: '⌃', action: 'ctrl' },
			{ code: 'AltLeft', key: '⌥', action: 'alt' },
			{ code: 'MetaLeft', key: '⌘', action: 'meta' },
			{ code: 'Space', key: '␣', action: 'space' },
			{ code: 'MetaRight', key: '⌘', action: 'meta' },
			{ code: 'AltRight', key: '⌥', action: 'alt' },
			{ code: 'ArrowLeft', key: '←', action: 'left' },
			{ code: 'ArrowUp', key: '↑', action: 'up' },
			{ code: 'ArrowDown', key: '↓', action: 'down' },
			{ code: 'ArrowRight', key: '→', action: 'right' },
		],
	],
	ru: [
		[
			{ code: 'IntlBackslash', key: '>', shiftKey: '<' },
			{ code: 'Digit1', key: '1', shiftKey: '!' },
			{ code: 'Digit2', key: '2', shiftKey: '"' },
			{ code: 'Digit3', key: '3', shiftKey: '№' },
			{ code: 'Digit4', key: '4', shiftKey: '%' },
			{ code: 'Digit5', key: '5', shiftKey: ':' },
			{ code: 'Digit6', key: '6', shiftKey: ',' },
			{ code: 'Digit7', key: '7', shiftKey: '.' },
			{ code: 'Digit8', key: '8', shiftKey: ';' },
			{ code: 'Digit9', key: '9', shiftKey: '(' },
			{ code: 'Digit0', key: '0', shiftKey: ')' },
			{ code: 'Minus', key: '-', shiftKey: '_' },
			{ code: 'Equal', key: '=', shiftKey: '+' },
			{ code: 'Backspace', key: '⌫', action: 'backspace' },
		],
		[
			{ code: 'Tab', key: '⇥', action: 'tab' },
			{ code: 'KeyQ', key: 'й', shiftKey: 'Й' },
			{ code: 'KeyW', key: 'ц', shiftKey: 'Ц' },
			{ code: 'KeyE', key: 'у', shiftKey: 'У' },
			{ code: 'KeyR', key: 'к', shiftKey: 'К' },
			{ code: 'KeyT', key: 'е', shiftKey: 'Е' },
			{ code: 'KeyY', key: 'н', shiftKey: 'Н' },
			{ code: 'KeyU', key: 'г', shiftKey: 'Г' },
			{ code: 'KeyI', key: 'ш', shiftKey: 'Ш' },
			{ code: 'KeyO', key: 'щ', shiftKey: 'Щ' },
			{ code: 'KeyP', key: 'з', shiftKey: 'З' },
			{ code: 'BracketLeft', key: 'х', shiftKey: 'Х' },
			{ code: 'BracketRight', key: 'ъ', shiftKey: 'Ъ' },
			{ code: 'Enter', key: '↵', action: 'enter' },
		],
		[
			{ code: 'CapsLock', key: '⇪', action: 'capslock' },
			{ code: 'KeyA', key: 'ф', shiftKey: 'Ф' },
			{ code: 'KeyS', key: 'ы', shiftKey: 'Ы' },
			{ code: 'KeyD', key: 'в', shiftKey: 'В' },
			{ code: 'KeyF', key: 'а', shiftKey: 'А' },
			{ code: 'KeyG', key: 'п', shiftKey: 'П' },
			{ code: 'KeyH', key: 'р', shiftKey: 'Р' },
			{ code: 'KeyJ', key: 'о', shiftKey: 'О' },
			{ code: 'KeyK', key: 'л', shiftKey: 'Л' },
			{ code: 'KeyL', key: 'д', shiftKey: 'Д' },
			{ code: 'Semicolon', key: 'ж', shiftKey: 'Ж' },
			{ code: 'Quote', key: 'э', shiftKey: 'Э' },
			{ code: 'Backslash', key: 'ё', shiftKey: 'Ё' },
		],
		[
			[
				{ code: 'ShiftLeft', key: '⇧', action: 'shift' },
				{ code: 'Backquote', key: ']', shiftKey: '[' },
				{ code: 'KeyY', key: 'я', shiftKey: 'Я' },
				{ code: 'KeyC', key: 'ч', shiftKey: 'Ч' },
				{ code: 'KeyD', key: 'с', shiftKey: 'С' },
				{ code: 'KeyV', key: 'м', shiftKey: 'М' },
				{ code: 'KeyJ', key: 'и', shiftKey: 'И' },
				{ code: 'KeyG', key: 'т', shiftKey: 'Т' },
				{ code: 'KeyM', key: 'ь', shiftKey: 'Ь' },
				{ code: 'Comma', key: 'б', shiftKey: 'Б' },
				{ code: 'Period', key: 'ю', shiftKey: 'Ю' },
				{ code: 'Slash', key: '/', shiftKey: '?' },
				{ code: 'ShiftRight', key: '⇧', action: 'shift' },
			],
			[
				{ code: 'ControlLeft', key: '⌃', action: 'ctrl' },
				{ code: 'AltLeft', key: '⌥', action: 'alt' },
				{ code: 'MetaLeft', key: '⌘', action: 'meta' },
				{ code: 'Space', key: '␣', action: 'space' },
				{ code: 'MetaRight', key: '⌘', action: 'meta' },
				{ code: 'AltRight', key: '⌥', action: 'alt' },
				{ code: 'ArrowLeft', key: '←', action: 'left' },
				{ code: 'ArrowUp', key: '↑', action: 'up' },
				{ code: 'ArrowDown', key: '↓', action: 'down' },
				{ code: 'ArrowRight', key: '→', action: 'right' },
			],
		],
	],
}

export default keyboardLayouts
